### ISSUE TITLE
Issue BG

### ISSUE THREAD

**Issue by GuM0x1a** [xubiuit/odoo_web_login#17]
Impacted versions: 11 Enterprise

Steps to reproduce: Enter at odoo url and see blank Background.

Current behavior:

login:20 GET https://192.168.2.17/web/content/12530-e8b4fe4/web.assets_common.0.css net::ERR_ABORTED 403 (FORBIDDEN)
login:21 GET https://192.168.2.17/web/content/14631-b77330e/web.assets_frontend.0.css net::ERR_ABORTED 403 (FORBIDDEN)
2login:23 GET https://192.168.2.17/web/content/14632-b77330e/web.assets_frontend.js net::ERR_ABORTED 403 (FORBIDDEN)
web.assets_common.js:3776 warning: Some modules could not be started
web.assets_common.js:3776 Missing dependencies: ["web.session"]
web.assets_common.js:3780 Non loaded modules: (9) ["web.AjaxService", "web_editor.base", "web_editor.ready", "web_editor.ace", "web.planner.common", "web_tour.TourManager", "web_tour.tour", "project_timesheet_synchro.test_screen_navigation", "account_reports.tour"]

Expected behavior:

Web login Background

![odoo_login_error](https://user-images.githubusercontent.com/39883453/51443666-1a268800-1cb2-11e9-806e-05a0d7bfb27f.png)
![odoo_login_error_sources](https://user-images.githubusercontent.com/39883453/51443667-1abf1e80-1cb2-11e9-9e9d-4047f95c55e6.PNG)

**Comment by xubiuit** [comment]
@urbmend26 please turn on your debug mode with assets then check, with your information above, I cannot help.

**Comment by rwngallego** [comment]
I get 404 not found with the default background, any clues about what's happening?

**Comment by GuM0x1a** [comment]
@rwngallego Upload the error log and a screenshot of the web login.

**Comment by rwngallego** [comment]
It's was solved by your suggestions in other threads. It was a chown -R issue. Thanks!

**Comment by xubiuit** [comment]
you're welcome
